### ISSUE TITLE
ClassCastException when sending VideoContent

### ISSUE THREAD

**Issue by bo0tzz** [JavaTelegramBot-API/JavaTelegramBot-API#29]
The API throws an exception anytime I send a GIF to a chat, it seems to be an internal issue.

`An error occurred during an event, check the stacktrace below for a more detailed error.
java.lang.ClassCastException: pro.zackpollard.telegrambot.api.internal.chat.message.content.DocumentContentImpl cannot be cast to pro.zackpollard.telegrambot.api.chat.message.content.VideoContent
        at pro.zackpollard.telegrambot.api.TelegramBot.sendMessage(TelegramBot.java:398)
        at pro.zackpollard.telegrambot.api.internal.chat.SuperGroupChatImpl.sendMessage(SuperGroupChatImpl.java:58)
        at me.bo0tzz.rnmbot.RnMListener.getGIF(RnMListener.java:106)
        at me.bo0tzz.rnmbot.RnMListener.onCommandMessageReceived(RnMListener.java:77)
        at pro.zackpollard.telegrambot.api.internal.event.ListenerRegistryImpl.lambda$callEvent$3(ListenerRegistryImpl.java:64)
        at java.lang.Iterable.forEach(Iterable.java:75)
        at pro.zackpollard.telegrambot.api.internal.event.ListenerRegistryImpl.callEvent(ListenerRegistryImpl.java:64)
        at pro.zackpollard.telegrambot.api.internal.updates.RequestUpdatesManager$UpdaterRunnable.run(RequestUpdatesManager.java:161)
        at java.lang.Thread.run(Thread.java:745)
`

Relevant code is at https://github.com/bo0tzz/RickAndMortyBot/blob/master/src/main/java/me/bo0tzz/rnmbot/RnMListener.java#L106

**Comment by zackpollard** [comment]
Please provide a stacktrace from the latest version of the API

**Comment by bo0tzz** [comment]
Here you go, from the 0.8.2 version of the API.
`An error occurred during an event, check the stacktrace below for a more detailed error.
java.lang.ClassCastException: pro.zackpollard.telegrambot.api.internal.chat.message.content.DocumentContentImpl cannot be cast to pro.zackpollard.telegrambot.api.chat.message.content.VideoContent
        at pro.zackpollard.telegrambot.api.TelegramBot.sendMessage(TelegramBot.java:409)
        at pro.zackpollard.telegrambot.api.internal.chat.SuperGroupChatImpl.sendMessage(SuperGroupChatImpl.java:58)
        at me.bo0tzz.rnmbot.RnMListener.getGIF(RnMListener.java:106)
        at me.bo0tzz.rnmbot.RnMListener.onCommandMessageReceived(RnMListener.java:77)
        at pro.zackpollard.telegrambot.api.internal.event.ListenerRegistryImpl.lambda$callEvent$3(ListenerRegistryImpl.java:65)
        at java.lang.Iterable.forEach(Iterable.java:75)
        at pro.zackpollard.telegrambot.api.internal.event.ListenerRegistryImpl.callEvent(ListenerRegistryImpl.java:65)
        at pro.zackpollard.telegrambot.api.internal.updates.RequestUpdatesManager$UpdaterRunnable.run(RequestUpdatesManager.java:161)
        at java.lang.Thread.run(Thread.java:745)
`

**Comment by bo0tzz** [comment]
After changing from using SendableVideoMessage to SendableDocumentMessage the issue is fixed on my side. I will still leave this issue open so you can add checks to the API.
